### PR TITLE
Refactoring/data types

### PR DESCRIPTION
**Pull request by NagayamaRyoga**

### CODE REVIEW

**Comment by makitsukasa** [comment]
```
3.079/ 0.948, 0.250, 0.180, 0.863, 0.838
3.079/ 0.948, 0.250, 0.180, 0.863, 0.838
3.079/ 0.948, 0.250, 0.180, 0.863, 0.838
3.079/ 0.948, 0.250, 0.180, 0.863, 0.838
3.079/ 0.948, 0.250, 0.180, 0.863, 0.838
続行するには何かキーを押してください . . .
```

**Comment by NagayamaRyoga** [comment]
`[3.079: Fitness]/[:RawFitness] [0.948, 0.250, 0.180, 0.863, 0.838:Gene]`
Output nothing if `null`.

**Comment by NagayamaRyoga** [comment]
#3

**Comment by makitsukasa** [comment]
Initializer is for emulate MGG/JGG. See initializer_JGG in GAQueue/src/benchmark.cpp

**Comment by NagayamaRyoga** [comment]
Still unneeded.
Just rewrite `new GAQSystem(..., initializer)` as `new GAQSystem(..., initializer())`.

**Pull request merged**
